### PR TITLE
docs: Add Authgear SDKs for Readme file

### PR DESCRIPTION
**Pull request by Boburmirzo**
Update README file with Authgear SDK libraries info:

https://github.com/authgear

### CODE REVIEW

**Comment by Boburmirzo** [comment]
> @Boburmirzo fix
> 
> image

Thanks! It is fixed now.

**Comment by Boburmirzo** [comment]
@hsluoyz I signed the CLA but somehow I used another email when I did the first commit but the GitHub account was the same. Is it fine?

**Comment by hsluoyz** [comment]
@Boburmirzo plz make it pass

image

**Comment by Boburmirzo** [comment]
@hsluoyz I created another PR for this fix.

https://github.com/casbin/awesome-auth/pull/28

**Pull request closed without merging**
